FROM oven/bun:1

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./apps/websocket ./apps/websocket

RUN bun install
RUN DATABASE_URL=no bun run db:generate

EXPOSE 8081

CMD ["bun", "run", "start:websocket"]

# Without docker compose - Manually : run in the root dir
# docker build -t todo-app-websocket -f ./docker/Dockerfile.websocket .